<a href="https://colab.research.google.com/github/arikaran007/ML-Prediction/blob/main/spam_detector/Spam_detector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df =pd.read_csv('/content/Youtube01-Psy.csv')
df.head()

COMMENT_ID            AUTHOR  \
0  LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU         Julius NM   
1  LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A       adam riyati   
2  LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8  Evgeny Murashkin   
3          z13jhp0bxqncu512g22wvzkasxmvvzjaz04   ElNino Melendez   
4          z13fwbwp1oujthgqj04chlngpvzmtt3r3dw            GsMega   

                  DATE                                            CONTENT  \
0  2013-11-07T06:20:48  Huh, anyway check out this you[tube] channel: ...   
1  2013-11-07T12:37:15  Hey guys check out my new channel and our firs...   
2  2013-11-08T17:34:21             just for test I have to say murdev.com   
3  2013-11-09T08:28:43   me shaking my sexy ass on my channel enjoy ^_^    
4  2013-11-10T16:05:38            watch?v=vtaRGgvGtWQ   Check this out .   

   CLASS  
0      1  
1      1  
2      1  
3      1  
4      1

In [ ]:
len(df)

350

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [ ]:
dvec = cv.fit_transform(df['CONTENT'])

In [ ]:
dvec

<350x1418 sparse matrix of type '<class 'numpy.int64'>'
	with 4354 stored elements in Compressed Sparse Row format>

In [ ]:
analyze = cv.build_analyzer()

In [ ]:
print(df['CONTENT'][320])
analyze(df['CONTENT'][320])

If the shitty Chinese Government didn't block YouTube over there, there'd  be close to 3 billion views right now. 


['if',
 'the',
 'shitty',
 'chinese',
 'government',
 'didn',
 'block',
 'youtube',
 'over',
 'there',
 'there',
 'be',
 'close',
 'to',
 'billion',
 'views',
 'right',
 'now']

In [ ]:
shufle = df.sample(frac=1)

In [ ]:
y = df['CLASS']
y

0      1
1      1
2      1
3      1
4      1
      ..
345    0
346    0
347    1
348    1
349    0
Name: CLASS, Length: 350, dtype: int64

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

cv = CountVectorizer()


x_att = cv.fit_transform(df['CONTENT'])


x_train_att, x_test_att, y_train, y_test = train_test_split(x_att, y, test_size=0.1, random_state=42)


clf = RandomForestClassifier(n_estimators=80)
clf.fit(x_train_att, y_train)

accuracy = clf.score(x_test_att, y_test)
print("Accuracy:", accuracy)


Accuracy: 0.9428571428571428


In [ ]:
from sklearn.metrics import confusion_matrix
pred = clf.predict(x_test_att)
confusion_matrix(y_test,pred)

array([[14,  2],
       [ 0, 19]])

In [ ]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, x_train_att, y_train, cv=5)
scores.mean()

0.9587301587301587

In [ ]:
df = pd.concat([pd.read_csv('/content/Youtube01-Psy.csv'),
                pd.read_csv('/content/Youtube02-KatyPerry.csv'),
                pd.read_csv('/content/Youtube03-LMFAO.csv'),
                pd.read_csv('/content/Youtube04-Eminem.csv'),
                pd.read_csv('/content/Youtube05-Shakira.csv')])

In [ ]:
df['CLASS'].value_counts()

1    1005
0     951
Name: CLASS, dtype: int64

In [ ]:
dshuf = df.sample(frac=1)
d_content = dshuf['CONTENT']
d_label = dshuf['CLASS']

In [ ]:
from sklearn.pipeline import Pipeline,make_pipeline
pl = Pipeline([
 ('bag of words: ', CountVectorizer()),
 ('Random Forest Classifier:', RandomForestClassifier())])
make_pipeline(CountVectorizer(), RandomForestClassifier())

Pipeline(steps=[('countvectorizer', CountVectorizer()),
                ('randomforestclassifier', RandomForestClassifier())])

In [ ]:
pl.fit(d_content[:1500],d_label[:1500])

Pipeline(steps=[('bag of words: ', CountVectorizer()),
                ('Random Forest Classifier:', RandomForestClassifier())])

In [ ]:
pl.score(d_content[:1500],d_label[:1500])

1.0

In [ ]:
pl.predict(["What a nice video"])

array([0])

In [ ]:
pl.predict(["Plz subscribe my channel"])

array([1])

In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer
pl_2 = make_pipeline(CountVectorizer(), TfidfTransformer(norm=None),
 RandomForestClassifier())

In [ ]:
scores = cross_val_score(pl_2, d_content, d_label, cv=5)
scores.mean()

0.9565439219165928